version: 1.0.0

client:
  organization: org1
  logging:
    level: info
  cryptoconfig:
    path: ../fixtures/crypto

  credentialStore:
    path: "/tmp/state-store"
    cryptoStore:
      path: /tmp/msp
  
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

channels:
  assetschannel:
    orderers:
      - orderer.org0.example.com

    peers:
      peer1.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer2.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0

organizations:
  org1:
    mspid: Org1MSP
    cryptoPath:  peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp
    peers:
      - peer1.org1.example.com
      - peer2.org1.example.com
    certificateAuthorities:

  ordererorg:
    mspID: "OrdererMSP"
    cryptoPath: ordererOrganizations/example.com/users/{username}@example.com/msp

orderers:
  orderer.org0.example.com:
    url: 127.0.0.1:7050

    grpcOptions:
      ssl-target-name-override: orderer.org0.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false 

    tlsCACerts:
      path: ../fixtures/crypto/ordererOrganizations/org0.example.com/orderers/orderer.org0.example.com/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem

peers:
  peer1.org1.example.com:
    url: 127.0.0.1:7051
    eventUrl: 127.0.0.1:7053

    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

    tlsCACerts:
      path: ../fixtures/crypto/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem

entityMatchers:
  peer:
    # the below matcher will allow dynamic discovery to use the anchor peer (peer0.org1.example.com)
    # as a template for all org1 discovered peers config
    - pattern: (\w+).org1.example.com:(\d+)
      urlSubstitutionExp: ${1}.org1.example.com:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org1.example.com
      mappedHost: peer1.org1.example.com

    - pattern: (\w+).org2.example.com:(\d+)
      urlSubstitutionExp: ${1}.org2.example.com:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org2.example.com
      mappedHost: peer1.org2.example.com